dist: focal
cache:
  bundler: true
  directories:
    - $HOME/docker
branches:
  only:
  - main
services:
  - docker
before_install:
  - chmod -R 777 .
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
install:
  # Set up Conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - rm miniconda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Set up environment
  - conda env create -f environment.yml
  - conda activate wdss-research-website
  # Set up Node/Hexo
  - npm install -g hexo-cli
  - npm install
before_script:
  - python build/build.py
script:
  - hexo generate
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
  fqdn: dev.research.wdss.io

