language: minimal
branches:
  only:
  - master
install:
  # Set up Conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Set up environment
  - conda env create -f environment.yml
  - conda activate wdss-research-website
  # Set up Node/Hexo
  - npm install -g hexo-cli
  - npm install
before_script:
  - ls -al  # debug
  - python build/build.py
script:
  - hexo generate

